apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-test-cluster
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/saidineshkalluri/test-cluster-2.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: argo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true
