apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saidineshkalluri/test-cluster-2.git
    path: dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
