apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-workflow-template
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: task1
            template: task1
          - name: task2
            template: task2
            dependencies: [task1]
          - name: task3
            template: task3
            dependencies: [task1]
          - name: task4
            template: task4
            dependencies: [task2, task3]
          - name: task5
            template: task5
            dependencies: [task4]
    - name: task1
      container:
        image: alpine:latest
        command: ["sh", "-c"]
        args: ["echo Task 1, this is final test"]
    - name: task2
      container:
        image: alpine:latest
        command: ["sh", "-c"]
        args: ["echo Task 2"]
    - name: task3
      container:
        image: alpine:latest
        command: ["sh", "-c"]
        args: ["echo Task 3"]
    - name: task4
      container:
        image: alpine:latest
        command: ["sh", "-c"]
        args: ["echo Task 4"]
    - name: task5
      container:
        image: alpine:latest
        command: ["sh", "-c"]
        args: ["echo Task 5"]
